### ISSUE TITLE
Ønsker å finne nettsiden til nada

### ISSUE THREAD

**Issue by MikAoJk** [navikt/nada#36]
Ønsker å finne følgende url i repoet: https://docs.knada.io

Denne kan man enten legge eks i readme.md, man kan evt legge det til som, website i about delen for repoet, eller legge det til i beskrivelsen av repoet, dette får å raskt finne frem til nettsiden, bare ved å gå via repoet

**Comment by Kyrremann** [comment]
Kunne du brukt litt flere ord for å beskrive hva du ønsker?

**Comment by MikAoJk** [comment]
> Kunne du brukt litt flere ord for å beskrive hva du ønsker?

Jepp hadde litt dårlig tid når eg lagde den, skal utfylle
